app:
  host: http://pastebox.ru
  public_list_size: 10
spring.application.name: paste
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: jeffrey
    password: Za7riNomGo2segotZa7riNomGo2segot**
    initialization-mode: always